[package]
name = "hold"
version = "0.3.1"
edition = "2024"
license = "MIT"
build = "build.rs"
repository = "https://github.com/BoltzExchange/hold"

[profile.release]
strip = true
opt-level = 2
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1.0.98"
cln-plugin = "0.4.0"
diesel = { version = "2.2.11", features = [
    "postgres",
    "r2d2",
    "chrono",
    "sqlite",
] }
diesel_migrations = "2.2.0"
log = { version = "0.4.27", features = [] }
prost = "0.13.4"
rcgen = { version = "0.13.2", features = ["x509-parser"] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread", "sync"] }
tonic = { version = "0.13.1", features = [
    "prost",
    "gzip",
    "zstd",
    "tls-aws-lc",
] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.137", features = ["preserve_order"] }
lightning-invoice = { version = "0.33.2", features = ["std"] }
chrono = { version = "0.4.41", features = ["serde"] }
bitcoin = { version = "0.32.6", features = ["rand-std"] }
secp256k1 = "0.29.1"
cln-rpc = "0.4.0"
hex = "0.4.3"
tokio-util = "0.7.15"
lightning = { version = "0.1.4", features = ["std"] }
bech32 = "0.11.0"

[build-dependencies]
built = { version = "0.8.0", features = ["git2"] }
tonic-build = "0.13.1"

[dev-dependencies]
mockall = "0.13.1"
