[package]
name = "hold"
version = "0.2.0"
edition = "2021"
license = "MIT"
build = "build.rs"
repository = "https://github.com/BoltzExchange/hold"

[profile.release]
strip = true
opt-level = 2
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1.0.93"
cln-plugin = "0.2.0"
diesel = { version = "2.2.4", features = ["postgres", "r2d2", "chrono", "sqlite"] }
diesel_migrations = "2.2.0"
log = { version = "0.4.22", features = [] }
prost = "0.13.3"
rcgen = { version = "0.13.1", features = ["x509-parser"] }
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread", "sync"] }
tonic = { version = "0.12.3", features = ["prost", "tls", "gzip", "zstd"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = { version = "1.0.132", features = ["preserve_order"] }
lightning-invoice = { version = "0.32.0", features = ["std"] }
chrono = { version = "0.4.38", features = ["serde"] }
bitcoin = { version = "0.32.4", features = ["rand-std"] }
secp256k1 = "0.29.1"
cln-rpc = "0.2.0"
hex = "0.4.3"
tokio-util = "0.7.12"

[build-dependencies]
built = { version = "0.7.5", features = ["git2"] }
tonic-build = "0.12.3"

[dev-dependencies]
mockall = "0.13.0"
