[tool.poetry]
name = "hold"
authors = ["Boltz"]
description = "Test for CLN hold invoice plugin"
version = "0.1.0"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
ruff = "^0.7.0"
grpcio = "^1.67.0"
grpcio-tools = "^1.67.0"
bolt11 = "^2.1.0"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = ["hold/protos"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D100", "D101", "D102", "D103", "D104", "D107", "D211", "D212", "S605", "D203", "ISC001", "COM812", "S101",
    "PLR2004", "PT011", "TCH001", "F403", "F405"
]
